# Gibbs MySQL Spyglass
# Copyright (C) 2016 AgilData
#
# This file is part of Gibbs MySQL Spyglass.
#
# Gibbs MySQL Spyglass is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Gibbs MySQL Spyglass is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Gibbs MySQL Spyglass.  If not, see <http:#www.gnu.org/licenses/>.

refresh_rate = 30

# [appenders.console]
# kind = "console"

# [[appenders.console.filter]]
# kind = "threshold"
# level = "error"

[appenders.file]
kind = "file"
path = "gibbs.log"
# pattern = "{d} [{t}] {l} {M}:{m}{n}"

[root]
level = "debug"
appenders = ["file"]

# [loggers."test::a"]
# level = "info"
# appenders = ["file"]
# additive = true
